
[[cls_6]]
== Détermination de l'((incertitude élargie))

[[scls_6-1]]
=== Introduction

[[scls_6-1-1]]
==== {blank}

La Recommandation INC-1(((Recommandation INC-1 (1980)))) (1980) du Groupe de travail sur l'expression des incertitudes(((Groupe de travail sur l'évaluation des incertitudes))), fondement de ce _Guide_ (voir l'<<cls_0>>), et les Recommandations 1 (CI-1981)(((Recommandation 1 (CI-1981), CIPM))) et 1 (CI-1986)(((Recommandation 1 (CI-1986), CIPM))) du ((CIPM)) qui approuvent et confirment INC-1(((Recommandation INC-1 (1980)))) (1980) (voir <<scls_A-2>> et <<scls_A-3>>) préconisent l'utilisation de l'((incertitude-type composée)) stem:[u_"c"(y)] comme paramètre pour exprimer quantitativement l'incertitude du résultat d'un mesurage. En effet, le ((CIPM)) a demandé par la seconde de ces Recommandations que ce qui est maintenant appelé ((incertitude-type composée))(((incertitude-type composée et comités consultatifs)))(((incertitude-type composée et comparaisons internationales))) stem:[u_"c"(y)] soit utilisé pour l'expression des résultats par «tous les participants aux comparaisons internationales et aux autres travaux effectués sous les auspices du ((CIPM)) et de ses Comités consultatifs».


[[scls_6-1-2]]
==== {blank}

Bien que stem:[u_"c"(y)] puisse être utilisé universellement pour exprimer l'incertitude d'un résultat de mesure, il est souvent nécessaire, pour certaines applications commerciales, industrielles ou réglementaires, ou lorsque cela concerne la santé ou la sécurité, de donner une mesure de l'incertitude qui définisse, autour du résultat de mesure, un intervalle à l'intérieur duquel on puisse espérer voir se situer une large fraction de la distribution des valeurs qui pourraient être raisonnablement attribuées au mesurande. Le Groupe de travail a reconnu l'existence de cette exigence et le paragraphe 5 de la Recommandation INC-1(((Recommandation INC-1 (1980)))) (1980) en est une conséquence. La Recommandation 1 (CI-1986)(((Recommandation 1 (CI-1986), CIPM))) du ((CIPM)) le reflète également.


[[scls_6-2]]
=== Incertitude élargie

[[scls_6-2-1]]
==== {blank}

La nouvelle mesure de l'incertitude qui satisfait à l'exigence de fournir un intervalle tel qu'indiqué en <<scls_6-1-2>> est appelée _((incertitude élargie))_ et se note stem:[ii(U)]. L'((incertitude élargie)) stem:[ii(U)] s'obtient en multipliant l'incertitude-type composée stem:[u_{"c"}(y)] par un _((facteur d'élargissement))_ stem:[k]:

[[eq_18]]
[stem]
++++
ii(U) = k u_{"c"} (y)
++++

Il est alors commode d'exprimer le résultat d'un mesurage sous la forme stem:[ii(Y) = y pm ii(U)], qui s'interprète comme signifiant que la meilleure estimation de la valeur attribuable au mesurande stem:[Y] est stem:[y], et qu'on peut s'attendre à ce que l'intervalle de stem:[y - ii(U)] à stem:[y + ii(U)] comprenne une fraction élevée de la distribution des valeurs qui pourraient être attribuées raisonnablement à stem:[ii(Y)]. Un tel intervalle s'exprime aussi par stem:[y - ii(U) <= ii(Y) <= y + ii(U)].

[[scls_6-2-2]]
==== {blank}

Les termes *((intervalle de confiance))* (<<scls_C-2-27>>, <<scls_C-2-28>>) et *((niveau de confiance))* (<<scls_C-2-29>>) ont des définitions spécifiques en statistique et s'appliquent seulement à l'intervalle défini par stem:[ii(U)] lorsque certaines conditions sont remplies, y compris celle que toutes les composantes de l'incertitude qui contribuent à stem:[u_{"c"}(y)] soient obtenues par des évaluations de Type A. En conséquence, dans ce _Guide_, on n'utilise pas le terme «intervalle de confiance» pour l'intervalle défini par stem:[ii(U)]; de même on n'utilise pas le terme «((niveau de confiance))*» (avec astérisque, correspondant en anglais à «confidence level») et on utilise le terme «((niveau de confiance))» (sans astérique, correspondant en anglais à «level of confidence») pris dans son sens littéral. Plus spécifiquement, stem:[ii(U)] est interprété comme définissant, autour du résultat de mesurage, un intervalle qui comprend une fraction élevée stem:[p] de la loi caractérisée par ce résultat et son incertitude-type composée et stem:[p] est la _((probabilité))_ ou _((niveau de confiance))_ de l'intervalle.


[[scls_6-2-3]]
==== {blank}

Chaque fois que cela est possible, le ((niveau de confiance)) stem:[p] associé à l'intervalle défini par stem:[ii(U)] doit être estimé et donné. On doit reconnaître que le fait de multiplier stem:[u_{"c"}(y)] par une constante ne fournit pas d'information nouvelle mais présente sous une forme différente l'information qui était déjà disponible. On doit aussi reconnaître que dans de nombreux cas, le ((niveau de confiance)) stem:[p] (spécialement pour les valeurs de stem:[p] voisines de 1) est quelque peu incertain, non seulement en raison d'une connaissance limitée de la loi de probabilité caractérisée par stem:[y] et stem:[u_{"c"}(y)] (particulièrement dans les régions extrêmes), mais aussi à cause de l'incertitude(((incertitude élargie))) de stem:[u_{"c"}(y)] elle-même (voir <<note2_2-3-5>>, <<scls_6-3-2>>, <<scls_6-3-3>> et <<annexG>>, particulièrement <<scls_G-6-6>>).

NOTE: Pour les formes qu'il est préférable d'utiliser pour présenter le résultat d'un mesurage suivant que l'on exprime l'incertitude par stem:[u_{"c"}(y)] ou par stem:[ii(U)], voir respectivement <<scls_7-2-2>> et <<scls_7-2-4>>.


[[scls_6-3]]
=== Choix d'un ((facteur d'élargissement))

[[scls_6-3-1]]
==== {blank}

La valeur du ((facteur d'élargissement)) stem:[k] est choisie sur la base du ((niveau de confiance)) requis pour l'intervalle stem:[y - ii(U)] à stem:[y + ii(U)]. En général, stem:[k] sera dans la plage de 2 à 3. Cependant, pour des applications spéciales, stem:[k] peut être choisi en dehors de cette plage. Une grande expérience et une connaissance étendue des utilisations dans lesquelles peut entrer un résultat de mesure peut faciliter le choix d'une valeur convenable pour stem:[k].

[[note_6-3-1]]
NOTE: On peut trouver parfois qu'une correction(((correction, non applicable d'une))) connue stem:[b] pour un effet systématique n'a pas été appliquée au résultat donné d'un mesurage mais qu'on a essayé de prendre l'effet en compte en élargissant l'«incertitude»(((incertitude lorsqu'on n'applique pas une correction))) affectée au résultat. Cela doit être évité. Ne pas appliquer de correction au résultat d'un mesurage pour un effet systématique significatif connu devrait être réservé à des circonstances très spéciales (voir <<scls_F-2-4-5>> pour un cas spécifique et son traitement). L'évaluation de l'incertitude d'un résultat de mesure ne doit pas être confondue avec l'attribution d'une limite de sécurité(((limites de sécurité))) à une grandeur donnée.


[[scls_6-3-2]]
==== {blank}

Idéalement, on aimerait pouvoir choisir une valeur spécifique du ((facteur d'élargissement)) stem:[k] qui fournisse un intervalle stem:[ii(Y) = y pm ii(U) = y pm k u_{"c"}(y)] correspondant à un ((niveau de confiance)) particulier stem:[p], tel que 95 ou 99 pour-cent; et, de manière équivalente, pour une valeur donnée de stem:[k], on aimerait pouvoir énoncer de manière non équivoque le ((niveau de confiance)) associé à cet intervalle. Il n'est cependant pas facile de le faire en pratique parce que cela nécessite une connaissance étendue de la loi de probabilité caractérisée par le résultat de mesure stem:[y] et son incertitude-type composée stem:[u_"c"(y)]. Bien que ces paramètres soient d'importance critique, ils sont par eux-mêmes insuffisants pour pouvoir établir des intervalles ayant des niveaux de confiance exactement connus.


[[scls_6-3-3]]
==== {blank}

La Recommandation INC-1(((Recommandation INC-1 (1980)))) (1980) ne spécifie pas comment l'on doit établir la relation entre stem:[k] et stem:[p]. Ce problème est traité en <<annexG>> et une méthode recommandée pour sa solution approximative est présentée en <<scls_G-4>> et résumée en <<scls_G-6-4>>. Cependant, une approche plus simple, présentée en <<scls_G-6-6>> convient souvent dans les situations de mesurage où la loi de probabilité caractérisée par stem:[y] et stem:[u_{"c"}(y)] est approximativement normale et où le nombre effectif de degrés de liberté(((degrés de liberté (nombre effectif de)))) de stem:[u_{"c"}(y)] est significativement grand. Lorsque c'est le cas, ce qui arrive fréquemment en pratique, on peut supposer que le choix de stem:[k = 2] fournit un intervalle ayant un ((niveau de confiance)) de 95 pour-cent environ et que le choix de stem:[k = 3] fournit un intervalle ayant un ((niveau de confiance)) de 99 pour-cent environ.

NOTE: Une méthode d'estimation du nombre effectif de degrés de liberté de stem:[u_{"c"}(y)] est donnée en <<scls_G-4>>. Le <<table_G-2>> de l'<<annexG>> peut être utilisé pour aider à décider de l'adéquation d'une solution à un mesurage particulier (voir <<scls_G-6-6>>).
