
[[cls_8]]
== Récapitulation de la procédure d'évaluation et d'expression de l'incertitude

Les étapes à suivre pour évaluer et exprimer l'incertitude(((incertitude, résumé de la procédure d'évaluation et d'expression de l'))) du résultat d'un mesurage, telles qu'elles sont présentées dans ce _Guide_, peuvent être résumées comme suit:

. Exprimer mathématiquement la relation entre le mesurande stem:[ii(Y)] et les grandeurs d'entrée stem:[ii(X)_i] dont stem:[ii(Y)] dépend: stem:[ii(Y) = f(ii(X)_1, ii(X)_2,..., ii(X)_N)]. La fonction stem:[f] doit contenir chaque grandeur, y compris toutes les corrections et facteurs de correction qui peuvent contribuer à une composante significative de l'incertitude du résultat du mesurage (voir <<scls_4-1-1>> et <<scls_4-1-2>>).
. Déterminer stem:[x_i], la valeur estimée de la grandeur d'entrée stem:[ii(X)_i], soit sur la base de l'analyse statistique de séries d'observations, soit par d'autres moyens (voir <<scls_4-1-3>>).
. Évaluer l'_incertitude-type_ stem:[u(x_i)] de chaque estimation stem:[x_i]. Pour une estimation d'entrée obtenue par l'analyse statistique de séries d'observations, l'incertitude-type est évaluée comme décrit en <<scls_4-2>> (_évaluation de Type A de l'incertitude-type_). Pour une estimation d'entrée obtenue par d'autres moyens, l'incertitude-type stem:[u(x_i)] est évaluée comme décrit en <<scls_4-3>> (_évaluation de Type B de l'incertitude-type_).
. Évaluer les covariances associées à toutes les estimations d'entrée qui sont corrélées (voir <<scls_5-2>>).
. Calculer le résultat du mesurage, c'est-à-dire l'estimation stem:[y] du mesurande stem:[ii(Y)], à partir de la relation fonctionnelle stem:[f] en utilisant pour les grandeurs d'entrée stem:[ii(X)_i] les estimations stem:[x_i] obtenues à l'étape 2 (voir <<scls_4-1-4>>).
. Déterminer l'_incertitude-type composée_ stem:[u_{"c"}(y)] du résultat de mesure stem:[y] à partir des incertitudes-types et des covariances associées aux estimations d'entrée, comme décrit à l'<<cls_5>>. Si le mesurage détermine simultanément plusieurs grandeurs de sortie, calculer leurs covariances (voir <<scls_7-2-5>>, <<scls_H-2>>, <<scls_H-3>>, et <<scls_H-4>>).
. S'il est nécessaire de donner une _incertitude élargie_ stem:[ii(U)], avec pour objectif de fournir un intervalle de stem:[y - ii(U)] à stem:[y + ii(U)] dont on peut s'attendre à ce qu'il comprenne une fraction élevée de la distribution des valeurs qui pourraient être attribuées raisonnablement au mesurande stem:[ii(Y)], multiplier l'incertitude-type composée stem:[u_{"c"}(y)] par un _facteur d'élargissement_ stem:[k], typiquement situé dans la plage de 2 à 3, pour obtenir stem:[ii(U) = k u_{"c"}(y)]. Choisir stem:[k] sur la base du niveau de confiance requis pour l'intervalle (voir<<scls_6-2>>, <<scls_6-3>> et spécialement l'<<annexG>> qui présente le choix d'une valeur de stem:[k] produisant un intervalle avec un niveau de confiance proche d'une valeur spécifiée).
. Donner dans un rapport le résultat du mesurage stem:[y] avec son incertitude-type composée stem:[u_{"c"}(y)] ou son incertitude élargie stem:[ii(U)] en suivant les indications données en <<scls_7-2-1>> ou <<scls_7-2-3>>. Utiliser l'un des modes d'expression recommandés en <<scls_7-2-2>> ou <<scls_7-2-4>>. Décrire, comme exposé aussi à l'<<cls_7>>, comment les valeurs de stem:[y] et stem:[u_{"c"}(y)] ou stem:[ii(U)] ont été obtenues.