
[[annexA]]
[appendix,obligation=normative]
== Recommandations du Groupe de travail et du ((CIPM))

[[scls_A-1]]
=== Recommandation INC-1 (1980)

index-range:inc1[(((Recommandation INC-1 (1980))))]Le Groupe de travail sur l'expression des incertitudes(((Groupe de travail sur l'évaluation des incertitudes))) (voir <<foreword>>) s'est réuni en octobre 1980 à l'initiative du Bureau international des poids et mesures \(((BIPM))) en réponse à une demande du Comité international des poids et mesures \(((CIPM))). Il a préparé un rapport détaillé pour prise en considération par le ((CIPM)), rapport qui se conclut par la Recommandation INC-1 (1980) <<KAARLS1981>>. Le texte français, qui fait autorité, déjà donné en <<scls_0-7>> de la présente version française, est reproduit ci-après <<KAARLS1981>>:

Expression des incertitudes expérimentales

*Recommandation INC-1 (1980)*

. L'incertitude d'un résultat de mesure comprend généralement plusieurs composantes qui peuvent être groupées en deux catégories d'après la méthode utilisée pour estimer leur valeur numérique:
+
--
.. celles qui sont évaluées à l'aide de méthodes statistiques,
.. celles qui sont évaluées par d'autres moyens.

Il n'y a pas toujours une correspondance simple entre le classement dans les catégories A ou B et le caractère «((aléatoire))» ou «systématique» utilisé antérieurement pour classer les incertitudes. L'expression «incertitude systématique» est susceptible de conduire à des erreurs d'interprétation; elle doit être évitée.

Toute description détaillée de l'incertitude devrait comprendre une liste complète de ses composantes et indiquer pour chacune la méthode utilisée pour lui attribuer une valeur numérique.
--
. Les composantes de la catégorie A sont caractérisées par les variances estimées stem:[s_i^2] (ou les «écart-types» estimés stem:[s_i]) et les nombres stem:[ii(nu)_i] de degrés de liberté. Le cas échéant, les covariances estimées doivent être données.
. Les composantes de la catégorie B devraient être caractérisées par des termes stem:[u_j^2] qui puissent être considérés comme des approximations des variances correspondantes dont on admet l'existence. Les termes stem:[u_j^2] peuvent être traités comme des variances et les termes stem:[u_j] comme des écarts-types. Le cas échéant, les covariances doivent être traitées de façon analogue.
. L'incertitude composée devrait être caractérisée par la valeur obtenue en appliquant la méthode usuelle de combinaison des variances. L'incertitude composée ainsi que ses composantes devraient être exprimées sous la forme d'«écart-types».
. Si pour des utilisations particulières on est amené à multiplier par un facteur l'incertitude composée afin d'obtenir une incertitude globale, la valeur numérique de ce facteur doit toujours être donnée.[[inc1]]


[[scls_A-2]]
=== Recommendation 1 (CI-1981)

index-range:ci1981[(((Recommandation 1 (CI-1981), CIPM)))]Le ((CIPM)) a examiné le rapport qui lui avait été soumis par le Groupe de travail sur l'expression des incertitudes(((Groupe de travail sur l'évaluation des incertitudes))) et il a adopté la recommandation suivante à sa 70e réunion tenue en octobre 1981 <<CIPM1982>>:

*Recommandation 1 (CI-1981)*

Expression des incertitudes expérimentales

Le Comité international des poids et mesures,

_considérant_

* la nécessité de convenir de modalités uniformes pour exprimer l'incertitude en métrologie,
* les efforts déployés dans ce but par divers organismes depuis de nombreuses années,
* les progrès encourageants vers une solution acceptable qui ont résulté des discussions du Groupe de travail sur l'expression des incertitudes réuni au ((BIPM)) en 1980,

_reconnaît_

* que les propositions du Groupe de travail pourraient constituer la base d'un accord éventuel pour l'expression des incertitudes,

_recommande_

* que les propositions de ce Groupe de travail soient largement portées à la connaissance des intéressés;
* que le ((BIPM)) s'efforce d'appliquer les principes contenus dans ces propositions aux comparaisons qu'il organisera dans les années à venir;
* que les autres organismes intéressés étudient et mettent à l'essai ces propositions et fassent connaître au ((BIPM)) leurs observations;
* que dans un délai de deux ou trois ans le ((BIPM)) fasse le point sur la mise en oeuvre de ces propositions.[[ci1981]]

[[scls_A-3]]
=== Recommandation 1 (CI-1986)

index-range:ci1986[(((Recommandation 1 (CI-1986), CIPM)))]Le ((CIPM)) a encore examiné le sujet de l'expression des incertitudes lors de sa 75e réunion tenue en octobre 1986 et il a adopté la recommandation suivante <<CIPM1987>>:(((Groupe de travail sur l'évaluation des incertitudes)))

*Recommandation 1 (CI-1986)*

Expression des incertitudes dans les travaux effectués sous les auspices du ((CIPM)) Le Comité international des poids et mesures,

_considérant_ la Recommandation INC-1(((Recommandation INC-1 (1980)))) (1980) adoptée par le Groupe de travail sur l'expression des incertitudes en 1980 et la Recommandation 1 (CI-1981)(((Recommandation 1 (CI-1981), CIPM))) adoptée par le ((CIPM)) en 1981 sur le même sujet,

_considérant_ que certains membres des comités consultatifs peuvent souhaiter des éclaircissements sur ces Recommandations pour les besoins des travaux qui leur incombent, en particulier pour les comparaisons internationales,

_prend acte_ de l'existence d'un groupe de travail de l'Organisation internationale de normalisation \(((ISO))), groupe commun à l'ISO, à l'organisation internationale de métrologie légale et à la Commission électrotechnique internationale(((CEI))), auquel collabore le ((CIPM)) et qui traite des applications particulières visées par le paragraphe 5 de la Recommandation INC-1 (1980), et entre autres des applications qui ont une portée commerciale,

_demande_ à tous les participants aux comparaisons internationales et aux autres travaux effectués sous les auspices du ((CIPM)) et de ses Comités consultatifs de suivre les directives données au paragraphe 4 de la Recommandation INC-1 (1980) et de donner avec leurs résultats l'incertitude(((incertitude-type composée et comités consultatifs)))(((incertitude-type composée et comparaisons internationales))) composée résultant des composantes de type A et de type B sous la forme _d'un écart-type_.[[ci1986]]
