

== Foreword

In 1997 a Joint Committee for Guides in Metrology http://www.bipm.org/en/committees/jc/jcgm/[JCGM],
chaired by the Director of the Bureau International des Poids et Mesures http://www.bipm.org/[BIPM],
was created by the seven international organizations that had originally in
1993 prepared the 'Guide to the expression of uncertainty in measurement' and
the 'International vocabulary of basic and general terms in metrology'.
The JCGM assumed responsibility for these two documents from the Technical Advisory
Group 4 of the International Organization for Standardization (ISO/TAG4).

The Joint Committee is formed by the http://www.bipm.org/[BIPM] with the International
Electrotechnical Commission (http://www.iec.ch/[IEC]), the International Federation
of Clinical Chemistry and Laboratory Medicine (http://www.ifcc.org/[IFCC]),
the International Laboratory Accreditation Cooperation (http://www.ilac.org/[ILAC]),
the International Organization for Standardization (http://www.iso.org/[ISO]),
the International Union of Pure and Applied Chemistry (http://www.iupac.org/[IUPAC]),
the International Union of Pure and Applied Physics (http://www.iupap.org/[IUPAP])
and the International Organization of Legal Metrology (http://www.oiml.org/[OIML]).

JCGM has two Working Groups. Working Group 1, 'Expression of uncertainty in
measurement',has the task to promote the use of the 'Guide to the expression
of uncertainty in measurement' and to prepare documents for its broad application.
Working Group 2, 'Working Group on International vocabulary of basic and general
terms in metrology', has the task to revise and promote the use of the 'International
vocabulary of basic and general terms in metrology' (the 'VIM').

In 2008 the JCGM made available a slightly revised version (mainly correcting
minor errors) of the 'Guide to the expression of uncertainty in measurement',
labelling the document 'JCGM 100:2008'.

In 2017 the JCGM rebranded the documents in its portfolio that have been produced
by Working Group 1 or are to be developed by that Group. The whole suite of
documents is now known as the 'Guide to the expression of uncertainty in measurement'
or 'GUM', and is concerned with the evaluation and expression of measurement
uncertainty, as well as its application in science, trade, health, safety and
other societal activities.

This part of the suite introduces the processes involved and the subsequent
parts in this suite giving specific guidance on these processes. This document
replaces <<jcgm104>>.

This document has been prepared by Working Group 1 of the JCGM, and has benefited
from detailed reviews undertaken by member organizations of the JCGM and National
Metrology Institutes.
