
[[cls_1]]
== Scope

The 'Guide to the expression of uncertainty in measurement' (GUM) establishes
general rules for evaluating and expressing uncertainty in measurement from
the shop floor to fundamental research. Therefore, the principles of this suite
of documents are intended to be applicable to a broad spectrum of measurements
and their applications. An overview of the parts of the GUM is given in <<table_a-1>>
in <<annex_a>>.

NOTE: Where the acronym GUM is used in this document, it refers to the suite
of documents. An individual part of the GUM is referred to by its corresponding
JCGM numbering (e.g., part 6 of the GUM is JCGM GUM-6:2020).

This document gives a rationale for evaluating, expressing and using measurement
uncertainty (<<cls_2>>). A brief introduction is given to measurement (<<cls_3>>)
and to the decisions involved when evaluating measurement uncertainty (<<cls_4>>).
In <<cls_5>>, a brief description of the contents of the parts of the GUM is
given. In each of these clauses, the relevant parts of the GUM are identified
for further guidance.
