
== Scope

This document provides guidance and procedures for assessing the conformity
of an item (entity, object or system) with specified requirements. The
item might be, for example, a gauge block, a grocery scale or a blood sample.
The procedures can be applied where the following conditions exist:

* the item is distinguished by a single scalar {{quantity}} (a measurable
property) defined to a level of detail sufficient to be reasonably represented
by an essentially unique true value;
+
NOTE: The GUM provides a rationale for not using the term 'true', but it
will be used in this document when there is otherwise a possibility of
ambiguity or confusion.

* an interval of permissible values of the property is specified by one
or two tolerance limits;

* the property can be measured and the {{measurement result}} expressed
in a manner consistent with the principles of the GUM, so that knowledge
of the value of the property can be reasonably described by (a) a {{probability
density function}} (PDF), (b) a {{distribution function}}, (c) numerical
approximations to such functions, or (d) a best estimate, together with
a coverage interval and an associated coverage probability.

The procedures developed in this document can be used to realize an interval,
called an acceptance interval, of permissible measured values of the property
of interest. Acceptance limits can be chosen so as to balance the risks
associated with accepting non-conforming items (consumer's risk) or rejecting
conforming items (producer's risk).

Two types of conformity assessment problems are addressed. The first is
the setting of acceptance limits that will assure that a desired conformance
probability for a single measured item is achieved. The second is the setting
of acceptance limits to assure an acceptable level of confidence on average
as a number of (nominally identical) items are measured. Guidance is given
for their solution.

This document contains examples to illustrate the guidance provided. The
concepts presented can be extended to more general conformity assessment
problems based on measurements of a set of scalar measurands. Documents
such as references <<ref19>>, <<ref13>> cover sector-specific aspects of
conformity assessment.

The audience of this document includes quality managers, members of standards
development organizations, accreditation authorities and the staffs of
testing and measuring laboratories, inspection bodies, certification bodies,
regulatory agencies, academics and researchers.